version: '3.9'

services:
  redis:
    image: redis:7.2.5
    ports:
      - "6379:6379"
  
  publisher:
    build:
      context: ./publisher
    ports:
      - "8000:8000"
    depends_on:
      - redis

  subscriber:
    build:
      context: ./subscriber
    depends_on:
      - redis